Repository ManageIQ/manageiq-api, pull requests merged in 2018-07, with the labels that each got.

#407 Add option to reuse dialog values for great justice on master
  app/controllers/api/mixins/service_templates.rb
  spec/requests/service_templates_spec.rb
Labels: bug, performance

#411 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#412 [DEPENDS ON ManageIQ/manageiq#17672] Add ServiceTemplate#schedules subcollection
  app/controllers/api/service_templates_controller.rb
  config/api.yml
  spec/requests/service_templates_spec.rb
Labels: blocker, gaprindashvili/yes

#416 Permit concurrent loads to avoid a deadlock
  lib/api/environment.rb
Labels: blocker, bug, gaprindashvili/yes

#414 Add DELETE service_templates/X/schedules/X
  app/controllers/api/service_templates_controller.rb
  config/api.yml
  spec/requests/service_templates_spec.rb
Labels: enhancement

#406 [GAPRINDASHVILI] Pass option to retain dialog values so they're not rerun
  app/controllers/api/mixins/service_templates.rb
  spec/requests/service_templates_spec.rb
Labels: blocker, bug, performance

#409 Moving the operations routine to a mixin
  app/controllers/api/mixins/operations.rb
  app/controllers/api/physical_switches_controller.rb
  spec/requests/physical_switches_spec.rb
Labels: providers/physical, refactoring

#420 Ensure MiqSchedule#name is unique
  spec/requests/service_templates_spec.rb
Labels: gaprindashvili/yes, test

#426 Ensure 'submit_workflow' is true when adding a service to a cart
  app/controllers/api/service_orders_controller.rb
  spec/requests/service_orders_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#427 Fixed validation while adding user with multiple groups.
  app/controllers/api/users_controller.rb
  spec/requests/users_spec.rb
Labels: bug

#430 Added support for fetching configuration scripts
  app/controllers/api/configuration_scripts_controller.rb
  config/api.yml
  spec/requests/configuration_scripts_spec.rb
Labels: enhancement

#424 Add event_streams as subcollection of the physical resources
  app/controllers/api/physical_chassis_controller.rb
  app/controllers/api/physical_servers_controller.rb
  app/controllers/api/physical_switches_controller.rb
  app/controllers/api/subcollections/event_streams.rb
  config/api.yml
  spec/requests/physical_chassis_spec.rb
  spec/requests/physical_servers_spec.rb
  spec/requests/physical_switches_spec.rb
Labels: enhancement

#417 Edit schedules for service templates
  app/controllers/api/reports_controller.rb
  app/controllers/api/service_templates_controller.rb
  app/controllers/api/subcollections/schedules.rb
  config/api.yml
  spec/requests/service_templates_spec.rb
Labels: blocker, enhancement, gaprindashvili/yes

#425 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#415 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-4
  CHANGELOG.md
Labels: documentation

#432 Fix logging tests after merging ManageIQ/manageiq #17227
  spec/requests/logging_spec.rb
Labels: refactoring

#431 Added verify_ssl to the list of valid attributes
  app/controllers/api/providers_controller.rb
Labels: enhancement

#433 [GAPRINDASHVILI] Add subresource_action_identifier spec helper
  spec/support/api/helpers.rb
Labels: test

#437 [RFE] Use Vmdb::Appliance.PRODUCT_NAME instead of calling i18n
  app/controllers/api/api_controller.rb
  spec/requests/entrypoint_spec.rb
Labels: enhancement

#421 Request cancel
  app/controllers/api/automation_requests_controller.rb
  app/controllers/api/mixins/resource_cancel.rb
  app/controllers/api/provision_requests_controller.rb
  app/controllers/api/request_tasks_controller.rb
  app/controllers/api/requests_controller.rb
  app/controllers/api/service_requests_controller.rb
  app/controllers/api/subcollections/request_tasks.rb
  app/controllers/api/subcollections/service_requests.rb
  config/api.yml
  spec/requests/automation_requests_spec.rb
  spec/requests/provision_requests_spec.rb
  spec/requests/request_tasks_spec.rb
  spec/requests/requests_spec.rb
  spec/requests/service_orders_spec.rb
  spec/requests/service_requests_spec.rb
  spec/requests/service_templates_spec.rb
  spec/support/api/helpers.rb
  spec/support/factory_overrides.rb
  spec/support/shared_examples/resource_cancel.rb
  spec/support/shared_examples/sub_resource_cancel.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#436 Symbolize schedule data
  app/controllers/api/subcollections/schedules.rb
  spec/requests/service_templates_spec.rb
Labels: bug, gaprindashvili/yes
