Repository ManageIQ/manageiq-api, pull requests merged in 2018-08, with the labels that each got.

#435 Allow the PUT/PATCH editing of templates and add a test for it
  app/controllers/api/templates_controller.rb
  config/api.yml
  spec/requests/templates_spec.rb
Labels: enhancement

#410 Adding Physical Chassis Location LED actions
  app/controllers/api/physical_chassis_controller.rb
  config/api.yml
  spec/requests/physical_chassis_spec.rb
Labels: enhancement, providers/physical

#439 Allow retirement requests to be created through the api
  config/api.yml
  spec/requests/requests_spec.rb
Labels: bug, enhancement, gaprindashvili/yes

#446 Fix failing specs due to model name in exception
  spec/requests/alerts_spec.rb
  spec/requests/service_orders_spec.rb
Labels: test

#440 Expose CloudSubnet creation
  app/controllers/api/subcollections/cloud_subnets.rb
  config/api.yml
  spec/requests/cloud_subnets_spec.rb
Labels: enhancement

#441 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation

#449 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#444 Include task_id in the response when invoking a custom button
  app/controllers/api/base_controller/generic.rb
Labels: bug, gaprindashvili/yes

#461 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation

#458 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-5
  CHANGELOG.md
Labels: documentation

#462 Allow bulk assignment and unassignment of tags for users
  config/api.yml
  spec/requests/users_spec.rb
Labels: enhancement

#455 Add best fit API for transformations moving vms to openstack
  app/controllers/api/transformation_mappings_controller.rb
  config/api.yml
  spec/requests/transformation_mappings_spec.rb
Labels: enhancement
