Repository ManageIQ/manageiq-api, pull requests merged in 2018-06, with the labels that each got.

#386 Ensure refresh => true option gets passed for service_template refresh
  app/controllers/api/subcollections/service_templates.rb
  spec/requests/service_catalogs_spec.rb
Labels: blocker, gaprindashvili/yes

#390 [Changelog] Update for Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#385 use request_admin_user?
  app/controllers/api/automation_requests_controller.rb
  app/controllers/api/provision_requests_controller.rb
  app/controllers/api/requests_controller.rb
  app/controllers/api/service_requests_controller.rb
  spec/requests/automation_requests_spec.rb
  spec/requests/provision_requests_spec.rb
  spec/requests/requests_spec.rb
  spec/requests/service_requests_spec.rb
  spec/support/api/helpers.rb
Labels: bug

#389 Add archive/activate actions to ServiceTemplate
  app/controllers/api/service_templates_controller.rb
  config/api.yml
  spec/requests/service_templates_spec.rb
Labels: enhancement

#391 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#382 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: technical debt, test

#392 Adding Physical Switch power action
  app/controllers/api/physical_switches_controller.rb
  config/api.yml
  spec/requests/physical_switches_spec.rb
Labels: enhancement

#400 Allow ordering ServiceTemplates with a schedule_time
  app/controllers/api/mixins/service_templates.rb
  app/controllers/api/service_templates_controller.rb
  app/controllers/api/subcollections/service_templates.rb
  spec/requests/service_templates_spec.rb
Labels: enhancement

#401 [WIP] Allow viewing ServiceTemplate Schedules
  app/controllers/api/mixins/service_templates.rb
  app/controllers/api/service_templates_controller.rb
  app/controllers/api/subcollections/service_templates.rb
  spec/requests/service_templates_spec.rb
Labels: wip

#403 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation

#404 In list of services, fetch RBAC-filtered vms subcollection
  app/controllers/api/subcollections/vms.rb
  spec/requests/services_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#402 Remove references to host provisioning
  config/api.yml
Labels: cleanup

#397 Creating PhysicalStorage controller and adding endpoint configuration
  app/controllers/api/physical_storages_controller.rb
  config/api.yml
  spec/requests/physical_storages_spec.rb
Labels: enhancement

#405 [GAPRINDASHVILI] Fix CI failure: correctly set @role before authentication
  spec/requests/services_spec.rb
Labels: bug, test
