Repository ManageIQ/manageiq-api, pull requests merged in 2018-05, with the labels that each got.

#371 Downcase userid to match how it is stored in the DB.
  lib/services/api/user_token_service.rb
  spec/lib/services/api/user_token_service_spec.rb
Labels: bug, gaprindashvili/yes

#376 Updated token manager initializer to log the configured server session_store
  lib/services/api/user_token_service.rb
Labels: enhancement

#372 Remove stubbing in settings integration specs
  app/controllers/api/settings_controller.rb
  lib/services/api/settings_filterer.rb
  spec/lib/services/api/settings_filterer_spec.rb
  spec/requests/settings_spec.rb
Labels: technical debt, test

#377 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#364 Adding support for collection_names whose plural and singular are the same
  config/routes.rb
  lib/api.rb
  lib/api/routing.rb
  spec/lib/api/routing_spec.rb
Labels: enhancement

#379 [Changelog] Update for Sprint 85
  CHANGELOG.md
Labels: documentation

#362 Creating PhysicalChassis controller and adding endpoint configuration
  app/controllers/api/physical_chassis_controller.rb
  config/api.yml
  spec/requests/physical_chassis_spec.rb
Labels: enhancement

#380 Adds request_retirement start
  app/controllers/api/base_controller/generic.rb
  config/api.yml
  spec/requests/services_spec.rb
  spec/requests/vms_spec.rb
Labels: enhancement

#383 Delete API for transformation_mappings
  config/api.yml
  spec/requests/transformation_mappings_spec.rb
Labels: enhancement

#370 Adding Physical Switches support
  app/controllers/api/physical_switches_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/physical_switches_spec.rb
Labels: enhancement
