Repository ManageIQ/manageiq-api, pull requests merged in 2018-03, with the labels that each got.

#333 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#334 Add pause and resume actions to Providers
  app/controllers/api/providers_controller.rb
  config/api.yml
  spec/requests/providers_spec.rb
Labels: enhancement

#332 Adding support for /api/containers primary collection.
  app/controllers/api/containers_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
Labels: enhancement, gaprindashvili/yes

#335 Added support for deleting data_stores
  app/controllers/api/data_stores_controller.rb
  config/api.yml
  spec/requests/data_stores_spec.rb
Labels: enhancement

#340 Fix specs after recent changes to RBAC
  spec/requests/collections_spec.rb
  spec/requests/custom_actions_spec.rb
  spec/requests/groups_spec.rb
  spec/requests/services_spec.rb
  spec/requests/users_spec.rb
Labels: gaprindashvili/yes

#339 Add networks subcollection to providers
  app/controllers/api/providers_controller.rb
  app/controllers/api/subcollections/networks.rb
  config/api.yml
  spec/requests/providers_spec.rb
Labels: enhancement

#338 Folders subcollection on providers
  app/controllers/api/providers_controller.rb
  app/controllers/api/subcollections/folders.rb
  config/api.yml
  spec/requests/providers_spec.rb
Labels: enhancement

#342 Add Lans subcollection to Hosts / Providers
  app/controllers/api/hosts_controller.rb
  app/controllers/api/providers_controller.rb
  app/controllers/api/subcollections/lans.rb
  config/api.yml
  spec/requests/hosts_spec.rb
  spec/requests/providers_spec.rb
Labels: enhancement

#343 Add svc_catalog_provision product feature to service dialog queries
  config/api.yml
  spec/requests/service_dialogs_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#344 Fix console specs to align with changes to console logic
  spec/requests/vms_spec.rb
Labels: bug/sporadic test failure, gaprindashvili/yes

#301 Queue chargeback reports of services
  app/controllers/api/services_controller.rb
  config/api.yml
  spec/requests/services_spec.rb
Labels: enhancement

#347 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#346 Add enterprise collection
  app/controllers/api/enterprises_controller.rb
  config/api.yml
  spec/requests/enterprises_spec.rb
Labels: enhancement

#348 Assign and Unassign alert definition profiles
  app/controllers/api/alert_definition_profiles_controller.rb
  app/controllers/api/mixins/tags.rb
  app/controllers/api/subcollections/tags.rb
  config/api.yml
  spec/requests/alert_definition_profiles_spec.rb
Labels: enhancement

#355 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation
