Repository ManageIQ/manageiq-api, pull requests merged in 2018-10, with the labels that each got.

#484 Fix policy spec due to new validation
  spec/requests/policies_spec.rb
Labels: test

#479 Logging cleanup
  app/controllers/api/base_controller/logger.rb
Labels: bug, cleanup

#472 Add basic CentralAdmin support to the API
  app/controllers/api/instances_controller.rb
  app/controllers/api/mixins/central_admin.rb
  app/controllers/api/vms_controller.rb
  spec/requests/instances_spec.rb
  spec/requests/vms_spec.rb
  spec/support/shared_examples/resource_power_operations.rb
Labels: bug, enhancement

#483 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_Api.pot
  locale/en/ManageIQ_Api.po
  locale/es/ManageIQ_Api.po
  locale/fr/ManageIQ_Api.po
  locale/ja/ManageIQ_Api.po
  locale/pt_BR/ManageIQ_Api.po
  locale/zanata.xml
  locale/zh_CN/ManageIQ_Api.po
Labels: internationalization

#487 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#488 Don't request HTTP Basic authenticaion when using a token
  app/controllers/api/base_controller/authentication.rb
  app/controllers/api/base_controller/logger.rb
  app/controllers/api/container_deployments_controller.rb
  spec/requests/authentication_spec.rb
Labels: bug, hammer/yes

#493 [GAPRINDASHVILI] These don't appear to be used and are causing test failures
  spec/requests/regions_spec.rb
Labels: test

#494 Test against a (ManageIQ) supported version of Postgres
  .travis.yml
Labels: dependencies, hammer/yes, test

#485 Add flag to initialize field default values
  app/controllers/api/mixins/service_templates.rb
  spec/requests/service_catalogs_spec.rb
  spec/requests/service_templates_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#492 [HAMMER] [Changelog] Add updates for beta1.1
  CHANGELOG.md
Labels: documentation

#497 Need the user on this call
  app/controllers/api/base_controller/generic.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#495 Add subcollection options support for CORS prefilghted requests
  app/controllers/api/base_controller.rb
  config/routes.rb
  spec/requests/tenant_quotas_spec.rb
Labels: enhancement, gaprindashvili/yes, hammer/yes

#476 Deny standalone service template ordering when product setting is enabled
  app/controllers/api/mixins/service_templates.rb
  spec/requests/service_catalogs_spec.rb
  spec/requests/service_templates_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#498 provide `service_template` to `orderable?` method
  app/controllers/api/mixins/service_templates.rb
Labels: bug, hammer/yes

#486 Post body changes for `validate_vms_resource ` to include service template_id
  app/controllers/api/transformation_mappings_controller.rb
  spec/requests/transformation_mappings_spec.rb
Labels: hammer/yes

#502 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation

#504 Ensure ServiceTemplate ordering passes through the submit_workflow flag
  app/controllers/api/mixins/service_templates.rb
  spec/requests/service_templates_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes
