Repository ManageIQ/manageiq-api, pull requests merged in 2018-04, with the labels that each got.

#328 Add delete action for templates
  app/controllers/api/subcollections/cloud_templates.rb
  config/api.yml
  spec/requests/cloud_templates_spec.rb
Labels: enhancement

#337 Add create action for templates
  app/controllers/api/subcollections/cloud_templates.rb
  config/api.yml
  spec/requests/cloud_templates_spec.rb
Labels: enhancement

#356 Enhanced API to catch Settings validation errors
  app/controllers/api/base_controller.rb
  spec/requests/servers_spec.rb
Labels: enhancement

#341 Add update action for templates
  app/controllers/api/subcollections/cloud_templates.rb
  config/api.yml
  spec/requests/cloud_templates_spec.rb
Labels: enhancement

#359 Always challenge a user with no/bad credentials
  app/controllers/api/base_controller.rb
  app/controllers/api/base_controller/authentication.rb
  spec/requests/authentication_spec.rb
Labels: bug

#363 Bump to ruby 2.3.6
  .travis.yml
Labels: test

#361 Adding tagging support for additional collections
  app/controllers/api/availability_zones_controller.rb
  app/controllers/api/cloud_networks_controller.rb
  app/controllers/api/cloud_subnets_controller.rb
  app/controllers/api/flavors_controller.rb
  app/controllers/api/network_routers_controller.rb
  app/controllers/api/security_groups_controller.rb
  config/api.yml
  spec/requests/tag_collections_spec.rb
Labels: enhancement

#367 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation

#309 Implementing change password action for providers endpoint
  app/controllers/api/providers_controller.rb
  config/api.yml
  spec/requests/providers_spec.rb
Labels: enhancement

#358 Add support for validate_vms action on transformation_mappings
  app/controllers/api/transformation_mappings_controller.rb
  config/api.yml
  spec/requests/transformation_mappings_spec.rb
Labels: enhancement
