Repository ManageIQ/manageiq-api, pull requests merged in 2018-02, with the labels that each got.

#317 Ensure request task options are keyed with symbols
  app/controllers/api/subcollections/request_tasks.rb
  spec/requests/automation_requests_spec.rb
  spec/requests/provision_requests_spec.rb
  spec/requests/requests_spec.rb
  spec/requests/service_requests_spec.rb
Labels: blocker, bug

#318 Do not return duplicate "edit" action entries
  app/controllers/api/base_controller/renderer.rb
  spec/requests/custom_buttons_spec.rb
Labels: bug

#319 Do not return hrefs for objects without a collection
  app/controllers/api/base_controller/renderer.rb
  spec/requests/service_templates_spec.rb
Labels: bug

#312 Deep symbolize keys when parsing options
  lib/services/api/request_parser.rb
  spec/lib/services/api/request_parser_spec.rb
Labels: bug

#310 [Changelog] Update for Sprint 78 and Gaprindashvili-1 release
  CHANGELOG.md
Labels: documentation

#308 Fix error message for required params on metric rollups subcollection
  lib/services/api/metric_rollups_service.rb
  spec/lib/services/api/metric_rollups_service_spec.rb
  spec/requests/services_spec.rb
Labels: bug

#321 Make cloud_tenants and flavors subcollections consistent with others
  app/controllers/api/subcollections/cloud_tenants.rb
  app/controllers/api/subcollections/flavors.rb
  spec/requests/cloud_tenants_spec.rb
  spec/requests/flavors_spec.rb
Labels: bug

#279 Allow additional provider parameters to be specified on create
  app/controllers/api/providers_controller.rb
  spec/requests/providers_spec.rb
Labels: enhancement

#306 Delete of search filters
  app/controllers/api/search_filters_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/search_filters_spec.rb
Labels: enhancement

#304 Add settings as a subcollection
  app/controllers/api/base_controller.rb
  app/controllers/api/base_controller/parser.rb
  app/controllers/api/base_controller/renderer.rb
  config/api.yml
  config/routes.rb
  spec/requests/regions_spec.rb
  spec/requests/servers_spec.rb
  spec/requests/zones_spec.rb
Labels: enhancement

#322 Ensure array is returned for subcollections
  app/controllers/api/subcollections/cloud_networks.rb
  app/controllers/api/subcollections/cloud_subnets.rb
  app/controllers/api/subcollections/security_groups.rb
  spec/requests/providers_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#311 Return product features for all of a user's groups on the API entrypoint
  app/controllers/api/api_controller.rb
  app/controllers/api/base_controller.rb
  spec/requests/authentication_spec.rb
Labels: enhancement

#323 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation

#313 Transformation Mappings Read and Create
  app/controllers/api/transformation_mappings_controller.rb
  config/api.yml
  spec/requests/transformation_mappings_spec.rb
Labels: enhancement, transformation

#316 Allow ordering of service templates resource
  app/controllers/api/mixins/service_templates.rb
  app/controllers/api/service_templates_controller.rb
  app/controllers/api/subcollections/service_templates.rb
  config/api.yml
  spec/requests/service_templates_spec.rb
Labels: enhancement, transformation

#325 Add lans collection with read and show
  app/controllers/api/lans_controller.rb
  config/api.yml
  spec/requests/lans_spec.rb
Labels: enhancement, transformation

#326 Set user when queueing VM actions
  app/controllers/api/base_controller/action.rb
  app/controllers/api/instances_controller.rb
  app/controllers/api/vms_controller.rb
  spec/requests/instances_spec.rb
  spec/requests/vms_spec.rb
Labels: bug

#278 Adding support to apply_config_pattern operation via the REST API
  app/controllers/api/physical_servers_controller.rb
  config/api.yml
  spec/requests/physical_servers_spec.rb
Labels: enhancement

#329 Raise bad request when current_group is specified on edit
  app/controllers/api/users_controller.rb
  spec/requests/users_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes

#330 Remove unused create_vm_attributes_hash method
  app/controllers/api/subcollections/vms.rb
Labels: cleanup

#327 Fix specifying of additional attributes on pictures
  app/controllers/api/mixins/pictures.rb
  app/controllers/api/pictures_controller.rb
  spec/requests/pictures_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#331 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation
