Repository ManageIQ/manageiq-api, pull requests merged in 2018-12, with the labels that each got.

#519 [Changelog] Update for Sprint 100
  CHANGELOG.md
Labels: documentation

#520 Fix invalid count query
  app/controllers/api/reports_controller.rb
  spec/requests/reports_spec.rb
Labels: blocker, bug, hammer/yes

#525 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#523 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#529 Updated service template's ui token info check to use token metadata for requester_type
  app/controllers/api/auth_controller.rb
  app/controllers/api/mixins/service_templates.rb
  lib/services/api/user_token_service.rb
  spec/requests/service_templates_spec.rb
Labels: bug

#530 [GAPRINDASHVILI] Updated service template's ui token info check to use token metadata for requester_type
  app/controllers/api/auth_controller.rb
  app/controllers/api/mixins/service_templates.rb
  lib/services/api/user_token_service.rb
  spec/requests/service_templates_spec.rb
Labels: blocker, bug

#531 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#526 Ensure a users own tasks are the only ones returned when the users role has View/My Tasks
  app/controllers/api/base_controller/renderer.rb
  app/controllers/api/tasks_controller.rb
  spec/requests/tasks_spec.rb
Labels: bug, hammer/yes
