Repository ManageIQ/manageiq-api, pull requests merged in 2018-09, with the labels that each got.

#428 EMS Cloud Refresh is missing
  config/api.yml
  spec/requests/providers_spec.rb
Labels: bug, gaprindashvili/yes

#466 Remove `modifier` to fix failing test
  spec/requests/conditions_spec.rb
Labels: test

#460 Apis for new servicey things
  app/controllers/api/service_offerings_controller.rb
  app/controllers/api/service_parameters_sets_controller.rb
  config/api.yml
  spec/requests/service_offerings_spec.rb
  spec/requests/service_parameters_sets_spec.rb
Labels: enhancement, gaprindashvili/no

#448 Pass changed dialog field values to resource_action_workflow
  app/controllers/api/base_controller/generic.rb
Labels: bug, gaprindashvili/yes

#468 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#465 Endpoint api/cloud_volume_types
  app/controllers/api/cloud_volume_types_controller.rb
  config/api.yml
  spec/requests/cloud_volume_types_spec.rb
Labels: enhancement, gaprindashvili/no

#463 Use the replacement backend method for searching and valiating VMs
  app/controllers/api/transformation_mappings_controller.rb
  spec/requests/transformation_mappings_spec.rb
Labels: enhancement, transformation

#467 transformation mappings `edit` action
  app/controllers/api/transformation_mappings_controller.rb
  config/api.yml
  spec/requests/transformation_mappings_spec.rb
Labels: enhancement

#473 Display plugins in the product_info under the root route
  app/controllers/api/api_controller.rb
Labels: gaprindashvili/no

#478 Change version now that hammer has been branched.
  lib/manageiq/api/version.rb
Labels: enhancement

#480 Pass `User#userid` instead of `User#id` to queue chargeback report
  app/controllers/api/services_controller.rb
  spec/requests/services_spec.rb
Labels: bug

#481 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#482 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
