Repository ManageIQ/manageiq-api, pull requests merged in 2018-11, with the labels that each got.

#505 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#503 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Api.po
  locale/fr/ManageIQ_Api.po
  locale/ja/ManageIQ_Api.po
  locale/pt_BR/ManageIQ_Api.po
  locale/zh_CN/ManageIQ_Api.po
Labels: internationalization

#490 Include product features list in the identity section of /api
  app/controllers/api/api_controller.rb
Labels: enhancement

#464 Add custom_button_events subcollection for users, tenants and groups
  app/controllers/api/groups_controller.rb
  app/controllers/api/subcollections/custom_button_events.rb
  app/controllers/api/tenants_controller.rb
  app/controllers/api/users_controller.rb
  config/api.yml
  spec/requests/groups_spec.rb
  spec/requests/tenants_spec.rb
  spec/requests/users_spec.rb
Labels: enhancement, gaprindashvili/no

#508 Seed tenant product features in Spec::Support::API::Helpers
  spec/support/api/helpers.rb
Labels: bug

#501 Add support for sui product features
  config/api.yml
  spec/lib/api/api_config_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#500 [Changelog] Add Hammer-B1 and Sprint 97
  CHANGELOG.md
Labels: documentation, hammer/no

#509 [HAMMER] [Changelog] Update for Hammer RC-1
  CHANGELOG.md
Labels: documentation

#510 [GAPRINDASHVILI] Add support for sui product features
  config/api.yml
  spec/lib/api/api_config_spec.rb
Labels: blocker, bug

#512 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#506 Custom Buttons with dialogs should be running invoke
  app/controllers/api/base_controller/generic.rb
  spec/requests/custom_actions_spec.rb
Labels: blocker, bug, hammer/yes

#517 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation

#513 Add more CRUD operations to conversion hosts, plus tags
  app/controllers/api/conversion_hosts_controller.rb
  config/api.yml
  spec/requests/conversion_hosts_spec.rb
Labels: blocker, hammer/yes
