Repository ManageIQ/manageiq-api, pull requests merged in 2019-10, with the labels that each got.

#675 Switch find_by_* to lookup_by_*
  app/controllers/api/alert_definition_profiles_controller.rb
  app/controllers/api/tags_controller.rb
Labels: ivanchuk/no, refactoring

#679 Include user info in widget generation
  app/controllers/api/widgets_controller.rb
  spec/requests/widgets_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes

#680 [FIX CI] Use visible attribute in services_spec
  spec/requests/services_spec.rb
Labels: test

#682 Expose the verify_credentials action for /api/providers
  app/controllers/api/providers_controller.rb
  config/api.yml
Labels: enhancement, ivanchuk/no

#683 [V2V] Added validations for the input params for conversion hosts.
  app/controllers/api/conversion_hosts_controller.rb
  spec/requests/conversion_hosts_spec.rb
Labels: enhancement

#684 Add tagging for cloud tenants
  app/controllers/api/cloud_tenants_controller.rb
  config/api.yml
  spec/requests/tag_collections_spec.rb
Labels: enhancement

#685 Add tagging for cloud volumes
  app/controllers/api/cloud_volumes_controller.rb
  config/api.yml
  spec/requests/tag_collections_spec.rb
Labels: enhancement

#686 Log exceptions to rails console
  app/controllers/api/base_controller.rb
Labels: enhancement

#688 The factory sets descriptions so we don't need to
  spec/requests/authentication_spec.rb
Labels: test

#690 Allow miq_regions to be edited, deleted
  app/controllers/api/regions_controller.rb
  config/api.yml
  spec/requests/regions_spec.rb
Labels: enhancement

#692 Hardening collections
  config/api.yml
  spec/lib/api/api_config_spec.rb
  spec/requests/enterprises_spec.rb
  spec/requests/roles_spec.rb
  spec/requests/servers_spec.rb
Labels: bug, test

#694 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test

#693 Refactor region and zone specs a bit
  spec/requests/regions_spec.rb
  spec/requests/zones_spec.rb
Labels: cleanup

#696 Sprint 123
  CHANGELOG.md
Labels: documentation

#697 Added some expected delete failures for zones
  spec/requests/zones_spec.rb
Labels: test
