Repository ManageIQ/manageiq-api, pull requests merged in 2019-08, with the labels that each got.

#642 Append RBAC features for VMRC console request through the API
  config/api.yml
Labels: changelog/yes, enhancement, hammer/no

#644 Destroy pxe_menu images upon removal
  app/controllers/api/pxe_servers_controller.rb
Labels: bug, ivanchuk/yes

#646 Adding ability to override encrypted attribute behavior in responses
  app/controllers/api/base_controller.rb
  app/controllers/api/base_controller/normalizer.rb
  app/controllers/api/service_dialogs_controller.rb
  spec/requests/service_dialogs_spec.rb
Labels: bug

#636 FirmwareRegistry create/list/delete and sync_fw_binaries
  app/controllers/api/firmware_registries_controller.rb
  config/api.yml
  spec/requests/firmware_registries_spec.rb
Labels: enhancement, ivanchuk/yes

#658 [Changelog] Update for Sprint 118
  CHANGELOG.md
Labels: documentation

#659 [Changelog] Update for Ivanchuk RC1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#650 Introduce the auth_key_pairs endpoint with set_ownership feature
  app/controllers/api/auth_key_pairs_controller.rb
  config/api.yml
  spec/requests/auth_key_pairs_spec.rb
Labels: enhancement, hammer/no, ivanchuk/no

#654 Specs for FirmwareRegistry updated
  spec/requests/firmware_registries_spec.rb
Labels: changelog/no, refactoring

#665 Change the feature identifier for listing auth key pairs
  config/api.yml
Labels: bug, ivanchuk/no

#555 Remove references to Tag where possible
  spec/requests/categories_spec.rb
  spec/requests/querying_spec.rb
  spec/requests/tags_spec.rb
Labels: test

#657 Spec for CustomButton virtual_attribute uri_attributes
  spec/requests/custom_buttons_spec.rb
Labels: test

#660 Add endpoints for widget content generation
  app/controllers/api/widgets_controller.rb
  config/api.yml
  spec/requests/widgets_spec.rb
Labels: enhancement

#666 Create TransformationMapping before Item (FIX CI FAILURE)
  app/controllers/api/transformation_mappings_controller.rb
  spec/requests/transformation_mappings_spec.rb
Labels: bug
