Repository ManageIQ/manageiq-api, pull requests merged in 2019-06, with the labels that each got.

#604 Fix v2v API specs after cluster validation changes
  spec/requests/transformation_mappings_spec.rb
Labels: test

#603 Support filtering for multiple IP
  lib/api/filter.rb
  spec/lib/api/filter_spec.rb
Labels: bug, enhancement, hammer/no

#596 Added create orchestration template service dialog action.
  app/controllers/api/service_dialogs_controller.rb
  config/api.yml
  spec/requests/service_dialogs_spec.rb
Labels: enhancement, hammer/no

#610 FIX CI: Parent_id should equals to nil - it is default value in request_specs
  spec/requests/requests_spec.rb
Labels: changelog/no, test

#598 Add a subcollection under VMs for displaying disks
  app/controllers/api/subcollections/disks.rb
  app/controllers/api/vms_controller.rb
  config/api.yml
  spec/requests/disks_spec.rb
Labels: changelog/yes, enhancement, hammer/no

#612 Avoid hardcoding paths to assets since it changes
  spec/requests/entrypoint_spec.rb
Labels: changelog/no, technical debt

#605 Add a subcollection under VMs for displaying CD-ROMs
  app/controllers/api/subcollections/cdroms.rb
  app/controllers/api/vms_controller.rb
  config/api.yml
  spec/requests/cdroms_spec.rb
Labels: changelog/yes, enhancement, hammer/no

#611 Improved request_spec by removing direct filtering by Classification#parent_id
  spec/requests/requests_spec.rb
Labels: bug, changelog/no, test

#608 Allow reconfigure vm on OSP provider over Centralized Administration
  config/api.yml
Labels: bug, changelog/yes

#615 [Changelog] Update for Sprint 114
  CHANGELOG.md
Labels: documentation

#613 Allow api.yml to be pluggable
  lib/api/api_config.rb
Labels: enhancement

#594 Added PxeServer create, update and delete actions
  app/controllers/api/pxe_menus_controller.rb
  app/controllers/api/pxe_servers_controller.rb
  app/controllers/api/subcollections/pxe_menus.rb
  config/api.yml
  spec/requests/pxe_servers_spec.rb
Labels: changelog/yes, enhancement
