Repository ManageIQ/manageiq-api, pull requests merged in 2019-05, with the labels that each got.

#582 [Changelog] Updated for Sprint 110
  CHANGELOG.md
Labels: documentation

#547 Add pagination and ordering to hash column MiqReporResult#result_set
  app/controllers/api/base_controller/parameters.rb
  app/controllers/api/results_controller.rb
  spec/requests/reports_spec.rb
Labels: enhancement

#586 Update comments for ConversionHostsController#create_resource method
  app/controllers/api/conversion_hosts_controller.rb
Labels: documentation

#583 Add scheduling option to automation requests as provision requests have
  spec/requests/automation_requests_spec.rb
Labels: changelog/no, enhancement, test

#566 Filter - add a new ===, !==, =~, !~ operators to match exact strings or regexes, without mangling
  lib/api/filter.rb
  spec/lib/api/filter_spec.rb
Labels: enhancement

#590 [Changelog] Update for Sprint 111
  CHANGELOG.md
Labels: documentation

#587 Remove conditional and assume plugin_name exists
  app/controllers/api/api_controller.rb
Labels: technical debt

#592 [Changelog] Update for Hammer-6
  CHANGELOG.md
Labels: documentation, hammer/yes

#593 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#600 Adjust ConversionHost support check so that it uses resource instead of singleton
  app/controllers/api/conversion_hosts_controller.rb
  spec/requests/conversion_hosts_spec.rb
Labels: hammer/yes, transformation

#599 Fix API retirement identifiers and role checking
  app/controllers/api/base_controller/generic.rb
  config/api.yml
  spec/requests/services_spec.rb
  spec/requests/vms_spec.rb
Labels: bug
