Repository ManageIQ/manageiq-api, pull requests merged in 2019-12, with the labels that each got.

#716 Remove old usage currency factories in chargebacks spec
  spec/requests/chargebacks_spec.rb
Labels: technical debt

#719 Fix custom_button_sets spec
  spec/requests/custom_button_sets_spec.rb
Labels: bug, test

#720 [IVANCHUK] Ivanchuk-2
  CHANGELOG.md
Labels: documentation

#721 Distinguish between SUI AJAX basic auth and regular basic auth
  app/controllers/api/base_controller/authentication.rb
Labels: bug, hammer/yes, ivanchuk/yes
