Repository ManageIQ/manageiq-api, pull requests merged in 2019-02, with the labels that each got.

#548 Add delete automate domain support
  app/controllers/api/automate_domains_controller.rb
  config/api.yml
  spec/requests/automate_domains_spec.rb
Labels: enhancement, hammer/no

#553 Don't use Tag when updating tag name
  app/controllers/api/tags_controller.rb
Labels: technical debt

#550 One semaphore to exclusively load them all
  lib/api/environment.rb
Labels: bug, gaprindashvili/yes, hammer/yes

#556 [Changelog] Update for Sprint 104
  CHANGELOG.md
Labels: documentation
