Repository ManageIQ/manageiq-api, pull requests merged in 2019-03, with the labels that each got.

#559 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes

#562 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#560 Remove openshift deployment
  app/controllers/api/container_deployments_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/container_deployments_spec.rb
Labels: hammer/no, technical debt

#563 GenericObject spec - fix failures after core PR
  spec/requests/generic_objects_spec.rb
Labels: bug/sporadic test failure

#546 TransformationMapping: API for adding mapping item
  app/controllers/api/transformation_mappings_controller.rb
  config/api.yml
  spec/requests/transformation_mappings_spec.rb
Labels: enhancement, transformation

#565 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#564 Remove references to MiqPassword
  app/controllers/api/base_controller/authentication.rb
  spec/requests/authentication_spec.rb
  spec/requests/logging_spec.rb
Labels: technical debt

#568 Update supported ruby versions on Travis
  .travis.yml
Labels: technical debt

#569 [Changelog] Update for Hammer-4
  CHANGELOG.md
Labels: documentation, hammer/yes
