Repository ManageIQ/manageiq-api, pull requests merged in 2019-11, with the labels that each got.

#695 Allow Servers to be edited and deleted
  app/controllers/api/servers_controller.rb
  config/api.yml
  spec/requests/servers_spec.rb
Labels: enhancement

#702 Replace display with visible in services specs.
  spec/requests/services_spec.rb
Labels: test

#707 PXE menu editing: Protect user's work
  app/controllers/api/pxe_servers_controller.rb
Labels: bug

#698 Fix call to generate_content
  app/controllers/api/widgets_controller.rb
  spec/requests/widgets_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes

#711 ignore ordering for authentication_spec
  spec/requests/authentication_spec.rb
Labels: bug/sporadic test failure, test

#713 Use Currency model instead of ChargebackRateDetailCurrency
  config/api.yml
  spec/requests/collections_spec.rb
Labels: technical debt
