Repository ManageIQ/manageiq-api, pull requests merged in 2019-01, with the labels that each got.

#536 Authorise action managing tenant quotas for according tenants in API
  app/controllers/api/base_controller/renderer.rb
  app/controllers/api/subcollections/quotas.rb
  spec/requests/tenant_quotas_spec.rb
  spec/requests/tenants_spec.rb
Labels: blocker, enhancement, hammer/yes

#538 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#537 Remove SQL select from exception error messages.
  app/controllers/api/base_controller/authentication.rb
  lib/services/api/error_serializer.rb
  spec/lib/services/api/error_serializer_spec.rb
Labels: bug, hammer/yes

#540 [Changelog] Update for Sprint 102
  CHANGELOG.md
Labels: documentation

#542 Do not request for basic auth if the auth_requester is set to UI
  app/controllers/api/base_controller/authentication.rb
Labels: bug, hammer/yes

#543 Allow authentication against the _vmdb_session cookie for UI only
  app/controllers/api/base_controller.rb
  app/controllers/api/base_controller/authentication.rb
  spec/requests/authentication_spec.rb
Labels: hammer/no

#545 [Changelog] Update for Sprint 103
  CHANGELOG.md
Labels: documentation

#549 Provide the path to the custom branding assets instead of booleans
  app/controllers/api/api_controller.rb
Labels: bug
