Repository ManageIQ/manageiq-api, pull requests merged in 2019-04, with the labels that each got.

#572 Added logic to support both string and symbol access to keys in dialog hash under options
  lib/services/api/request_parser.rb
  spec/lib/services/api/request_parser_spec.rb
Labels: bug

#576 Fix poor wording on missing resource error message.
  app/controllers/api/base_controller/parser.rb
  spec/requests/policies_spec.rb
Labels: bug, hammer/no

#577 [Changelog] Update for Hammer-5 release
  CHANGELOG.md
Labels: documentation, hammer/yes

#579 Include a list of supported providers in `OPTIONS /api/providers`
  app/controllers/api/providers_controller.rb
  spec/requests/providers_spec.rb
Labels: enhancement

#571 Add create Git backed automation domain
  app/controllers/api/automate_domains_controller.rb
  config/api.yml
  spec/requests/automate_domains_spec.rb
Labels: bug, enhancement, hammer/no

#557 Performance updates for virtual_attribute_search
  app/controllers/api/base_controller/renderer.rb
  spec/requests/services_spec.rb
Labels: bug, performance

#581 Include the regions if they're supported with OPTIONS /api/providers
  app/controllers/api/providers_controller.rb
Labels: changelog/yes, enhancement, hammer/no

#578 Support physical server provisioning
  app/controllers/api/customization_templates_controller.rb
  app/controllers/api/pxe_images_controller.rb
  app/controllers/api/pxe_servers_controller.rb
  app/controllers/api/subcollections/customization_templates.rb
  app/controllers/api/subcollections/pxe_images.rb
  config/api.yml
  spec/requests/customization_templates_spec.rb
  spec/requests/pxe_images_spec.rb
  spec/requests/pxe_servers_spec.rb
Labels: enhancement
