Repository ManageIQ/manageiq-api, pull requests merged in 2019-07, with the labels that each got.

#618 [Changelog] Update for Hammer-8
  CHANGELOG.md
Labels: documentation, hammer/yes

#623 [Changelog] Update for Sprint 115
  CHANGELOG.md
Labels: documentation

#624 Fix the broken spec for auto approver.
  spec/requests/automation_requests_spec.rb
  spec/requests/requests_spec.rb
Labels: test

#625 There's no need to use gettext in specs
  spec/requests/providers_spec.rb
Labels: technical debt

#626 Rename the "Cloud Intel" menu item to "Overview"
  spec/requests/reports_spec.rb
Labels: changelog/no, enhancement, hammer/no

#597 Support firmware update
  app/controllers/api/physical_servers_controller.rb
  app/controllers/api/subcollections/firmware_binaries.rb
  config/api.yml
  spec/requests/physical_servers_spec.rb
Labels: enhancement

#621 Update RBAC features for HTML5 remote consoles
  config/api.yml
Labels: enhancement, hammer/no

#627 [Changelog] Update for Hammer-9
  CHANGELOG.md
Labels: documentation, hammer/yes

#628 Add server_info.release
  app/controllers/api/api_controller.rb
  spec/requests/entrypoint_spec.rb
Labels: enhancement

#616 Create dialog from template - generic endpoint
  app/controllers/api/service_dialogs_controller.rb
  config/api.yml
  spec/requests/service_dialogs_spec.rb
Labels: changelog/yes, enhancement, hammer/no

#629 Adding support for Collection action
  app/controllers/api/base_controller/manager.rb
Labels: enhancement, ivanchuk/yes

#633 Expose Tenant Groups as a separate endpoint
  app/controllers/api/tenant_groups_controller.rb
  config/api.yml
  spec/requests/tenant_groups_spec.rb
Labels: enhancement, ivanchuk/no

#631 keys should be symbolized before merge
  app/controllers/api/hosts_controller.rb
  spec/requests/hosts_spec.rb
Labels: bug, ivanchuk/yes

#635 [Changelog] Update for Ivanchuk Beta1 release
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
