Repository ManageIQ/manageiq-api, pull requests merged in 2019-09, with the labels that each got.

#668 [Changelog] Rollup of releases for Ivanchuk-1
  CHANGELOG.md
Labels: documentation

#669 Refactor and update the transformation mapping specs
  spec/requests/transformation_mappings_spec.rb
Labels: test

#656 Expose error messages from ServiceTemplate.orderable?
  app/controllers/api/mixins/service_templates.rb
  spec/requests/service_templates_spec.rb
Labels: enhancement, ivanchuk/yes

#674 Update vms_spec.rb
  spec/requests/vms_spec.rb
Labels: test

#673 update_attrs has been deprecated
  app/controllers/api/base_controller/generic.rb
  app/controllers/api/custom_buttons_controller.rb
  app/controllers/api/generic_object_definitions_controller.rb
  app/controllers/api/generic_objects_controller.rb
  app/controllers/api/policies_controller.rb
  app/controllers/api/providers_controller.rb
  app/controllers/api/roles_controller.rb
  app/controllers/api/subcollections/custom_attributes.rb
  app/controllers/api/tags_controller.rb
  app/controllers/api/transformation_mappings_controller.rb
  app/controllers/api/vms_controller.rb
  spec/requests/entrypoint_spec.rb
  spec/requests/generic_object_definitions_spec.rb
  spec/requests/instances_spec.rb
  spec/requests/physical_servers_spec.rb
  spec/requests/querying_spec.rb
  spec/requests/reports_spec.rb
  spec/requests/service_dialogs_spec.rb
  spec/requests/service_requests_spec.rb
  spec/requests/services_spec.rb
  spec/requests/vms_spec.rb
Labels: technical debt

#677 Remove useless param methods in ResultsController
  app/controllers/api/base_controller/parameters.rb
Labels: technical debt

#645 Expose DDF schema for a provider when asking using OPTIONS + type
  app/controllers/api/providers_controller.rb
  spec/requests/providers_spec.rb
Labels: enhancement, hammer/no, ivanchuk/no

#678 Fixes the pxe_servers collection actions
  config/api.yml
  spec/requests/pxe_servers_spec.rb
Labels: bug, ivanchuk/yes
