Repository ManageIQ/manageiq-api, pull requests merged in 2020-08, with the labels that each got.

#873 Allow set_ownership action for service templates
  config/api.yml
  spec/requests/custom_actions_spec.rb
  spec/requests/set_ownership_spec.rb
Labels: bug

#881 fix alert definitions specs
  spec/requests/alert_definitions_spec.rb
Labels: bug, test

#883 allow specification of sort_order with abbreviation or full form
  app/controllers/api/base_controller/parameters.rb
  spec/requests/querying_spec.rb
Labels: enhancement
