Repository ManageIQ/manageiq-api, pull requests merged in 2020-03, with the labels that each got.

#760 Alphabetize the constants and includes
  app/controllers/api/providers_controller.rb
Labels: cleanup

#762 Change master version number after Jansa branch
  lib/manageiq/api/version.rb
Labels: enhancement

#764 Expose ConfigurationProfiles primary and sub collection
  app/controllers/api/configuration_profiles_controller.rb
  app/controllers/api/providers_controller.rb
  app/controllers/api/subcollections/configuration_profiles.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/providers_spec.rb
Labels: enhancement

#765 Expose ConfiguredSystems
  app/controllers/api/configured_systems_controller.rb
  app/controllers/api/providers_controller.rb
  app/controllers/api/subcollections/configured_systems.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/providers_spec.rb
Labels: enhancement

#767 [WIP] Add ARCHITECTURE.md
  ARCHITECTURE.md
Labels: wip

#773 ServiceOrder base class is no longer valid, prefer ServiceOrderCart
  app/controllers/api/service_orders_controller.rb
  spec/requests/service_orders_spec.rb
Labels: enhancement, ivanchuk/no, jansa/yes?

#761 Differentiate between ems_cloud and infra for rbac purposes for providers collection
  app/controllers/api/providers_controller.rb
  config/api.yml
  spec/requests/providers_spec.rb
  spec/support/api/helpers.rb
Labels: bug

#774 Add helper method for multiple subcollection_action_identifiers
  spec/support/api/helpers.rb
Labels: enhancement

#772 Move API OIDC/OAuth2 support from API to ManageIQ core
  app/controllers/api/base_controller/authentication.rb
Labels: refactoring

#779 [IVANCHUK] Changelog Ivanchuk-4
  CHANGELOG.md
Labels: documentation

#783 Add the custom_attributes subcollection to hosts collection
  app/controllers/api/hosts_controller.rb
  config/api.yml
  spec/requests/hosts_spec.rb
Labels: enhancement, ivanchuk/yes, jansa/yes?

#784 [JANSA] Update CHANGELOG.MD
  CHANGELOG.md
Labels: documentation

#785 Update normalizer.rb
  app/controllers/api/base_controller/normalizer.rb
Labels: documentation

#787 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#788 /api/product_info - fix missing support_website, support_website_text
  app/controllers/api/api_controller.rb
  spec/requests/entrypoint_spec.rb
Labels: bug, jansa/yes?

#786 ensure ids in dialog field values are normalized
  app/controllers/api/base_controller/normalizer.rb
  spec/requests/service_dialogs_spec.rb
Labels: bug, jansa/yes
