Repository ManageIQ/manageiq-api, pull requests merged in 2020-10, with the labels that each got.

#905 Added api for adding new physical storage
  app/controllers/api/physical_storages_controller.rb
  config/api.yml
  spec/requests/physical_storages_spec.rb
Labels: enhancement

#927 Allow patch/put/delete methods on the CloudNetwork resource
  config/api.yml
Labels: enhancement

#900 Add action "revoke sessions" to users_controllers
  app/controllers/api/users_controller.rb
  config/api.yml
  spec/requests/users_spec.rb
Labels: enhancement

#931 Allow PATCH/PUT methods for editing on the services endpoint
  config/api.yml
Labels: enhancement

#929 Make the actions endpoint RESTful by setting its verb to gpppd
  config/api.yml
Labels: enhancement

#933 [Renderer] Fix duplicate includes with extra_cols
  app/controllers/api/base_controller/renderer.rb
  spec/requests/providers_spec.rb
Labels: performance

#921 Make the auth key pair creating asynchronous
  app/controllers/api/auth_key_pairs_controller.rb
  spec/requests/auth_key_pairs_spec.rb
Labels: bug

#845 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-api.gemspec
Labels: developer

#930 Expose the MiqAction types on the endpoint using OPTIONS
  app/controllers/api/actions_controller.rb
Labels: enhancement

#937 Allow PATCH/PUT editing of rates (chargeback)
  config/api.yml
Labels: enhancement

#934 Allow PATCH/PUT editing of policy_profiles
  config/api.yml
Labels: enhancement

#935 Allow PATCH/PUT editing of alert_definition_profiles
  config/api.yml
Labels: enhancement

#941 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: bug, developer

#940 [Renderer] Use next, not return
  app/controllers/api/base_controller/renderer.rb
  spec/requests/providers_spec.rb
Labels: bug, jansa/yes

#946 [requests/providers_spec.rb] Jansa approved spec
  spec/requests/providers_spec.rb
Labels: test

#947 Handle DDF type API_ATTRIBUTES in AuthenticationsSpec
  spec/requests/authentications_spec.rb
Labels: bug, test

#948 Only show OPTIONS for supported providers
  app/controllers/api/providers_controller.rb
  spec/requests/providers_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?
