Repository ManageIQ/manageiq-api, pull requests merged in 2020-06, with the labels that each got.

#854 Fix CI: Remove non-existent identifiers in miq_product_features.yml
  config/api.yml
Labels: bug, jansa/yes?

#847 Allow to pass chargeback relations by id or href in rates collection
  app/controllers/api/base_controller/normalizer.rb
  app/controllers/api/chargeable_fields_controller.rb
  app/controllers/api/rates_controller.rb
  config/api.yml
  spec/requests/chargeable_fields_spec.rb
  spec/requests/chargebacks_spec.rb
  spec/requests/rates_spec.rb
Labels: enhancement, jansa/yes?

#851 Placeholder string for Float::INFINITY in response
  app/controllers/api/base_controller/normalizer.rb
  spec/requests/chargebacks_spec.rb
Labels: bug, jansa/yes?

#857 Fixed specs for global region initiated requests
  spec/support/shared_examples/resource_power_operations.rb
Labels: bug, ivanchuk/yes, jansa/yes?, test

#856 Adding an authentication section in product_info
  app/controllers/api/api_controller.rb
  spec/requests/entrypoint_spec.rb
Labels: enhancement, jansa/yes

#859 Expose tag category description in chargeback_assignment
  app/controllers/api/mixins/chargeback_assignment.rb
  spec/requests/chargebacks_spec.rb
Labels: enhancement, jansa/yes?
