Repository ManageIQ/manageiq-api, pull requests merged in 2020-04, with the labels that each got.

#789 Update bin/update, yeah, it's a typo fix
  bin/update
Labels: bug

#792 fix rails 5.2 json parse
  lib/api/create_constraint.rb
Labels: bug, jansa/yes?

#791 Add async KeyPair deletion
  app/controllers/api/auth_key_pairs_controller.rb
  spec/requests/auth_key_pairs_spec.rb
Labels: enhancement

#795 Adding support for check_compliance action on vms
  app/controllers/api/vms_controller.rb
  config/api.yml
  spec/requests/vms_spec.rb
Labels: enhancement

#766 Added test for returning the policies contained in the policy profiles assigned to a Vm
  spec/requests/policies_spec.rb
Labels: bug

#799 Adding support for check_compliance action on templates
  app/controllers/api/templates_controller.rb
  config/api.yml
  spec/requests/templates_spec.rb
Labels: enhancement, jansa/yes

#802 Add shared examples for check compliance action.
  spec/requests/templates_spec.rb
  spec/requests/vms_spec.rb
  spec/support/shared_examples/check_compliance_action.rb
Labels: jansa/yes, refactoring

#803 Adding support for check_compliance action on providers
  app/controllers/api/providers_controller.rb
  config/api.yml
  spec/requests/providers_spec.rb
Labels: enhancement, jansa/yes

#804 add tags as lan subcollection
  app/controllers/api/lans_controller.rb
  config/api.yml
  spec/requests/lans_spec.rb
Labels: enhancement

#815 Fix spec after ManageIQ/manageiq#19927
  spec/requests/conversion_hosts_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?, v2v

#809 Adding support for check_compliance action on instances
  app/controllers/api/instances_controller.rb
  config/api.yml
  spec/requests/instances_spec.rb
Labels: enhancement, jansa/yes

#811 Adding support for check_compliance action on host resources.
  app/controllers/api/hosts_controller.rb
  config/api.yml
  spec/requests/hosts_spec.rb
Labels: enhancement, jansa/yes

#806 Adding support for filter_expression in the groups
  app/controllers/api/groups_controller.rb
  spec/requests/groups_spec.rb
Labels: enhancement, jansa/yes

#812 Save visibility content as a symbol not as a string
  app/controllers/api/custom_buttons_controller.rb
  spec/requests/custom_buttons_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?, wip

#808 Validate report in report results in subcollection results
  app/controllers/api/subcollections/results.rb
  spec/requests/reports_spec.rb
Labels: bug, jansa/yes?

#807 Add pagination, ordering, filtering for result_set to report/results
  app/controllers/api/mixins/report_result_set.rb
  app/controllers/api/results_controller.rb
  app/controllers/api/subcollections/results.rb
  spec/requests/reports_spec.rb
  spec/support/shared_examples/report_results_set.rb
Labels: enhancement, jansa/yes

#819 Adding support for check_compliance action on cloud template resources
  app/controllers/api/cloud_templates_controller.rb
  config/api.yml
  spec/requests/cloud_templates_spec.rb
  spec/support/shared_examples/check_compliance_action.rb
Labels: enhancement, jansa/yes

#814 fix the custom button create
  app/controllers/api/custom_buttons_controller.rb
Labels: blocker, bug, ivanchuk/yes, jansa/yes?

#821 create the resource action after save for custom buttons
  app/controllers/api/custom_buttons_controller.rb
Labels: bug, ivanchuk/yes, jansa/yes?
