Repository ManageIQ/manageiq-api, pull requests merged in 2020-02, with the labels that each got.

#733 Call the `key?` method on objects safely when trying to normalize
  app/controllers/api/base_controller/normalizer.rb
Labels: enhancement, ivanchuk/no

#736 Reset the User.current_user upon each incoming request
  app/controllers/api/base_controller.rb
  app/controllers/api/base_controller/authentication.rb
Labels: enhancement

#738 Change the zone param to zone_name in DDF provider validation
  app/controllers/api/providers_controller.rb
Labels: bug

#735 snapshot_create - support :snapshot_name_optional? on RHV VMs
  app/controllers/api/subcollections/snapshots.rb
  spec/requests/snapshots_spec.rb
Labels: bug, ivanchuk/yes

#723 Extend the existing provider creation with DDF support
  app/controllers/api/providers_controller.rb
  spec/requests/providers_spec.rb
Labels: enhancement

#740 Remove container provider resume/pause
  app/controllers/api/providers_controller.rb
  config/api.yml
  spec/requests/providers_spec.rb
Labels: bug, technical debt

#737 Adding support for OpenID-Connect/OAuth2 in the API
  app/controllers/api/base_controller/authentication.rb
Labels: enhancement

#747 Adding support for OIDCProviderTokenEndpoint, OIDCOAuthIntrospectionEndpoint and OIDCScope
  app/controllers/api/base_controller/authentication.rb
Labels: enhancement, ivanchuk/yes

#742 Add compliances subcollection
  app/controllers/api/subcollections/compliances.rb
  app/controllers/api/vms_controller.rb
  config/api.yml
  spec/requests/compliances_spec.rb
Labels: enhancement, ivanchuk/yes

#728 Fix update of CustomButton to save ae_attributes
  app/controllers/api/custom_buttons_controller.rb
  spec/requests/custom_buttons_spec.rb
Labels: bug, ivanchuk/yes

#750 alphabetize the includes in the vm controller
  app/controllers/api/vms_controller.rb
Labels: cleanup

#746 changelog for sprint 129, 130
  CHANGELOG.md
Labels: documentation

#751 Include provider ID in the validation task arguments if available
  app/controllers/api/providers_controller.rb
Labels: enhancement

#749 Enable add and edit resource for /api/policy_profiles endpoint
  app/controllers/api/policy_profiles_controller.rb
  config/api.yml
  spec/requests/policies_spec.rb
Labels: enhancement, ivanchuk/yes

#741 Display provider authentications and endpoints when asking for it
  app/controllers/api/providers_controller.rb
  app/controllers/api/subcollections/endpoints.rb
  spec/requests/providers_spec.rb
Labels: enhancement, question

#752 Add deprecation mechanism to the config file.
  app/controllers/api/base_controller/logger.rb
  app/controllers/api/base_controller/parser.rb
Labels: enhancement

#705 Automate class CRUD
  app/controllers/api/automate_classes_controller.rb
  config/api.yml
  spec/requests/automate_classes_spec.rb
Labels: enhancement

#753 Extend the existing provider editing endpoint with DDF support
  app/controllers/api/providers_controller.rb
  config/api.yml
  spec/requests/providers_spec.rb
Labels: enhancement

#754 Create code owners for manageiq-api repo
  .github/CODEOWNERS
Labels: developer

#743 Call instance method for vm retire queueing
  app/controllers/api/vms_controller.rb
  spec/requests/vms_spec.rb
Labels: bug, ivanchuk/yes

#758 Remove ability to delete a region
  app/controllers/api/regions_controller.rb
  config/api.yml
  spec/requests/regions_spec.rb
Labels: bug, ivanchuk/yes

#759 Default zone needs to exist otherwise provider creation fails
  spec/requests/providers_spec.rb
Labels: test
