Repository ManageIQ/manageiq-api, pull requests merged in 2020-12, with the labels that each got.

#966 Fixed endpoint feature mapping for policy-related endpoints
  config/api.yml
Labels: bug, kasparov/no

#957 Add rename action for Vm.
  app/controllers/api/vms_controller.rb
  config/api.yml
  spec/requests/vms_spec.rb
Labels: enhancement

#973 Add the list of available rails timezones to the base endpoint
  app/controllers/api/api_controller.rb
Labels: enhancement, new endpoint

#971 Make api debuggable from browser again, accept cookie without csrf for GET
  app/controllers/api/base_controller/authentication.rb
Labels: enhancement

#943 Expose DDF for creating snapshots when calling OPTIONS
  app/controllers/api/subcollections/snapshots.rb
  app/controllers/api/vms_controller.rb
  spec/requests/vms_spec.rb
Labels: enhancement

#960 Add endpoint for editing Network Routers
  app/controllers/api/network_routers_controller.rb
  config/api.yml
  spec/requests/network_routers_spec.rb
Labels: enhancement
