Repository ManageIQ/manageiq-api, pull requests merged in 2020-11, with the labels that each got.

#959 Update vm specs for the new pause feature
  spec/requests/vms_spec.rb
Labels: bug, test

#958 Include end date to queryable filter parameters for metric rollups end point
  lib/services/api/metric_rollups_service.rb
  spec/requests/metric_rollups_spec.rb
Labels: bug

#932 Added api for remove physical storage
  app/controllers/api/physical_storages_controller.rb
  config/api.yml
  spec/requests/physical_storages_spec.rb
Labels: enhancement

#942 Expose POST/PATCH/PUT/DELETE actions on Cloud Tenants
  app/controllers/api/cloud_tenants_controller.rb
  config/api.yml
  spec/requests/cloud_tenants_spec.rb
Labels: enhancement

#969 Allow set ownership screen for instances and images
  config/api.yml
  spec/requests/set_ownership_spec.rb
Labels: bug
