Repository ManageIQ/manageiq-api, pull requests merged in 2020-07, with the labels that each got.

#860 add trace for easier debugging from failed service template create
  app/controllers/api/service_templates_controller.rb
Labels: enhancement

#862 Added a general rescue for ActiveRecord::RecordInvalid errors
  app/controllers/api/base_controller.rb
  spec/requests/service_catalogs_spec.rb
Labels: bug

#863 Add assignment type human readable to chargeback assigment mixin
  app/controllers/api/mixins/chargeback_assignment.rb
  spec/requests/chargebacks_spec.rb
Labels: enhancement, jansa/yes?

#864 Return an empty collection, instead of 500 server error, for providers that don't support configured_systems or configuration_profiles subcollections
  app/controllers/api/subcollections/configuration_profiles.rb
  app/controllers/api/subcollections/configured_systems.rb
  spec/requests/providers_spec.rb
Labels: bug, jansa/yes?

#876 Use shared example in set ownership screen spec
  spec/requests/set_ownership_spec.rb
  spec/support/shared_examples/set_ownership.rb
Labels: test

#875 Updated the API to return nil virtual attributes and associations
  app/controllers/api/base_controller/renderer.rb
  spec/requests/querying_spec.rb
  spec/requests/requests_spec.rb
Labels: enhancement

#879 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement
