Repository ManageIQ/manageiq-api, pull requests merged in 2020-01, with the labels that each got.

#729 Fix spec failure
  spec/requests/headers_spec.rb
Labels: bug, test

#730 Wrap possible autoloaded models in interlock loading
  app/controllers/api/providers_controller.rb
Labels: bug

#732 [V2V] Renaming openstack_tls_ca_cert variable
  app/controllers/api/conversion_hosts_controller.rb
Labels: enhancement, ivanchuk/yes, v2v
