Repository ManageIQ/manageiq-api, pull requests merged in 2020-05, with the labels that each got.

#826 Adding support for check_compliance action on container resources.
  app/controllers/api/container_groups_controller.rb
  app/controllers/api/container_images_controller.rb
  app/controllers/api/container_nodes_controller.rb
  config/api.yml
  spec/requests/container_groups_spec.rb
  spec/requests/container_images_spec.rb
  spec/requests/container_nodes_spec.rb
Labels: enhancement, jansa/yes

#813 add functionality to retire vms in future
  app/controllers/api/vms_controller.rb
  spec/requests/vms_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes

#810 [BaseController::Render] Cache role allows
  app/controllers/api/base_controller/renderer.rb
Labels: performance

#820 Fix the broken specs
  spec/requests/automate_classes_spec.rb
  spec/requests/automate_spec.rb
Labels: performance

#824 Chargeback rate assignment
  app/controllers/api/chargebacks_controller.rb
  app/controllers/api/container_images_controller.rb
  app/controllers/api/mixins/chargeback_assignment.rb
  config/api.yml
  spec/requests/chargebacks_spec.rb
  spec/support/shared_examples/assigments.rb
Labels: enhancement, jansa/yes?

#830 DDF: schema-based validation and revised create/update for providers
  app/controllers/api/providers_controller.rb
  spec/requests/providers_spec.rb
Labels: enhancement

#832 Add name to valid edit attrs for vms
  app/controllers/api/vms_controller.rb
  spec/requests/vms_spec.rb
Labels: bug, jansa/yes?

#834 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer, documentation

#835 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#836 Allow to specify chargebacks by hrefs in rate assignment
  app/controllers/api/mixins/chargeback_assignment.rb
  spec/support/shared_examples/assigments.rb
Labels: bug, jansa/yes?

#837 Chargeback rate assignment was not returning hrefs and assignment_prefix for tags in responses
  app/controllers/api/mixins/chargeback_assignment.rb
Labels: bug, jansa/yes

#839 Adding support for the request_download action on report results.
  app/controllers/api/base_controller/parser.rb
  app/controllers/api/base_controller/results.rb
  app/controllers/api/mixins/result_downloads.rb
  app/controllers/api/results_controller.rb
  app/controllers/api/tasks_controller.rb
  config/api.yml
  config/routes.rb
  lib/api/collection_config.rb
  spec/lib/api/api_config_spec.rb
  spec/requests/result_downloads_spec.rb
  spec/support/api/helpers.rb
Labels: enhancement

#841 Removing the disabled flag option for API actions.
  app/controllers/api/base_controller/parser.rb
  app/controllers/api/base_controller/renderer.rb
  config/api.yml
  lib/api/collection_config.rb
Labels: refactoring

#825 Added parts for the NSX-T provider
  app/controllers/api/cloud_networks_controller.rb
  app/controllers/api/network_services_controller.rb
  app/controllers/api/providers_controller.rb
  app/controllers/api/security_groups_controller.rb
  app/controllers/api/security_policies_controller.rb
  app/controllers/api/security_policy_rules_controller.rb
  app/controllers/api/subcollections/cloud_networks.rb
  app/controllers/api/subcollections/cloud_subnets.rb
  app/controllers/api/subcollections/network_services.rb
  app/controllers/api/subcollections/security_groups.rb
  app/controllers/api/subcollections/security_policies.rb
  app/controllers/api/subcollections/security_policy_rules.rb
  config/api.yml
Labels: enhancement

#853 Add a providers create action for physical infra
  config/api.yml
Labels: bug, jansa/yes?

#840 Fix API action identifier verification check spec.
  config/api.yml
  spec/lib/api/api_config_spec.rb
  spec/requests/widgets_spec.rb
Labels: bug, jansa/yes?

#846 Enhanced API System token authentication to work with OIDC and SAML.
  app/controllers/api/base_controller/authentication.rb
Labels: enhancement, jansa/yes
