Repository ManageIQ/manageiq-api, pull requests merged in 2021-05, with the labels that each got.

#1033 Allow creation of AutomationManagers via API
  config/api.yml
Labels: bug

#1038 Fix Provider create product feature
  config/api.yml
Labels: bug, lasker/yes?

#1037 Use the seed_specific_features method to accurately create features
  config/api.yml
  spec/requests/authentication_spec.rb
  spec/requests/result_downloads_spec.rb
  spec/requests/roles_spec.rb
  spec/requests/tenant_quotas_spec.rb
  spec/support/api/helpers.rb
Labels: bug, lasker/yes?

#1039 [BaseController::Render] Fix subquery_res.count
  app/controllers/api/base_controller/renderer.rb
  spec/requests/vms_spec.rb
Labels: bug, jansa/no, lasker/yes?

#1040 Fix spec that verifies features to actually see all features
  spec/lib/api/api_config_spec.rb
Labels: bug, lasker/yes?, test
