Repository ManageIQ/manageiq-api, pull requests merged in 2021-01, with the labels that each got.

#964 Created *gpppd endpoint for host aggregates
  app/controllers/api/host_aggregates_controller.rb
  config/api.yml
  spec/requests/host_aggregates_spec.rb
Labels: enhancement, kasparov/no

#975 [Subcollections::Results] Add DELETE actions
  app/controllers/api/subcollections/results.rb
  config/api.yml
  spec/requests/reports_spec.rb
Labels: enhancement

#962 Add endpoint for creating/editing/deleting floating IPs
  app/controllers/api/floating_ips_controller.rb
  config/api.yml
  spec/requests/floating_ips_spec.rb
Labels: enhancement

#983 Subclass Openstack StorageManagers
  spec/requests/providers_spec.rb
Labels: refactoring, test

#914 Expose the DDF schema for CloudVolume subclasses via OPTIONS
  app/controllers/api/cloud_volumes_controller.rb
  config/api.yml
  spec/requests/cloud_volumes_spec.rb
Labels: enhancement, question

#954 Expose EventDefinitionSets.
  app/controllers/api/event_definition_sets_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/event_definition_sets_spec.rb
Labels: enhancement

#987 Fix the error message at OPTIOS /api/cloud_volumes
  app/controllers/api/cloud_volumes_controller.rb
Labels: bug, kasparov/no

#988 Fix klass.superclass not matching with acts_as_leaf_class
  app/controllers/api/providers_controller.rb
Labels: bug

#984 Expose tenant quota definitions via OPTIONS
  app/controllers/api/tenants_controller.rb
  spec/requests/tenant_quotas_spec.rb
  spec/requests/tenants_spec.rb
Labels: enhancement, kasparov/no

#967 Fix storing ae_attributes as uri_attributes for create/edit in CustomButtons
  app/controllers/api/custom_buttons_controller.rb
  spec/requests/custom_buttons_spec.rb
Labels: bug

#981 Add endpoint for creating/updating/deleting PXE Customization Templates
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/customization_templates_spec.rb
Labels: enhancement, kasparov/no

#994 save after setting parent on vm update
  app/controllers/api/vms_controller.rb
Labels: bug

#995 Fix CI: Use owner to set group in widget factory
  spec/requests/widgets_spec.rb
Labels: test
