Repository ManageIQ/manageiq-api, pull requests merged in 2021-06, with the labels that each got.

#1043 [BaseController] Localize OPTIONS (allow optional user auth)
  app/controllers/api/base_controller.rb
  app/controllers/api/base_controller/authentication.rb
  spec/requests/providers_spec.rb
Labels: bug

#1047 Change to default unavailable/unsupported message for shelve operations on VMware VMs
  spec/requests/vms_spec.rb
Labels: refactoring

#1041 Replace ems_block_storage_* features with ems_storage_*
  config/api.yml
Labels: enhancement

#1050 Simplify validate_*_for_action methods
  app/controllers/api/instances_controller.rb
  app/controllers/api/vms_controller.rb
Labels: technical debt
