Repository ManageIQ/manageiq-api, pull requests merged in 2021-09, with the labels that each got.

#1066 New feature - Editing physical storage
  app/controllers/api/physical_storages_controller.rb
  config/api.yml
  spec/requests/physical_storages_spec.rb
Labels: enhancement, morphy/yes?

#1056 Add support for editing autosde cloud volume
  app/controllers/api/cloud_volumes_controller.rb
  spec/requests/cloud_volumes_spec.rb
Labels: enhancement, morphy/yes?

#1071 Add create network_router to the api
  app/controllers/api/network_routers_controller.rb
  config/api.yml
  spec/requests/network_routers_spec.rb
Labels: enhancement, providers/cloud, providers/network

#1076 properly pass audit information for tasks
  app/controllers/api/network_routers_controller.rb
  app/controllers/api/subcollections/cloud_templates.rb
  app/controllers/api/subcollections/flavors.rb
Labels: bug

#1072 Fix retirement api for instances
  config/api.yml
Labels: bug, morphy/yes?

#1078 rename params_for_edit to params_for_update
  app/controllers/api/cloud_networks_controller.rb
  spec/requests/cloud_networks_spec.rb
Labels: refactoring

#1070 Convert cloud volume operations to SupportsFeatureMixin
  app/controllers/api/cloud_volumes_controller.rb
Labels: refactoring
