Repository ManageIQ/manageiq-api, pull requests merged in 2021-07, with the labels that each got.

#1055 [LASKER] ems_automation_add_provider was from a refactoring on master, not lasker
  config/api.yml
Labels: bug

#1052 [Subcollection::AlertDefinitions] Fix unassign success
  app/controllers/api/subcollections/alert_definitions.rb
Labels: test

#1054 [GroupsController] Fix filter_expression save format
  app/controllers/api/groups_controller.rb
  spec/requests/groups_spec.rb
Labels: bug

#1060 Allow OPTIONS on /collection/:id for DDF resource params
  config/routes.rb
Labels: enhancement

#1062 Add list/show for Cloud Database collections
  app/controllers/api/cloud_database_flavors_controller.rb
  app/controllers/api/cloud_databases_controller.rb
  config/api.yml
  spec/requests/cloud_database_flavors_spec.rb
  spec/requests/cloud_databases_spec.rb
Labels: enhancement

#1061 [Api::Filter] Allow filtering '=' via arrays
  lib/api/filter.rb
  spec/lib/api/filter_spec.rb
Labels: enhancement

#1058 Added options call for cloud networks
  app/controllers/api/cloud_networks_controller.rb
  spec/requests/cloud_networks_spec.rb
Labels: enhancement
