Repository ManageIQ/manageiq-api, pull requests merged in 2021-02, with the labels that each got.

#990 Add endpoint for PXE Image Types
  app/controllers/api/pxe_image_types_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/pxe_image_types_spec.rb
Labels: enhancement, kasparov/no

#991 Add spec for GET /api/event_definition_sets/:id/events
  spec/requests/event_definition_sets_spec.rb
Labels: enhancement, test

#992 Add endpoint for ISO datastores
  app/controllers/api/iso_datastores_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/iso_datastores_spec.rb
Labels: enhancement, kasparov/no

#1001 Compare user id with current user id with the right type
  app/controllers/api/users_controller.rb
Labels: bug

#1002 Add Subcollections::Settings
  app/controllers/api/base_controller.rb
  app/controllers/api/regions_controller.rb
  app/controllers/api/servers_controller.rb
  app/controllers/api/subcollections/settings.rb
  app/controllers/api/zones_controller.rb
  lib/services/api/settings_filterer.rb
  spec/lib/services/api/settings_filterer_spec.rb
Labels: refactoring

#1003 [Api::SettingsFilterer] Remove excessive branching logic
  lib/services/api/settings_filterer.rb
Labels: refactoring

#985 Implement define host initiator
  app/controllers/api/host_initiators_controller.rb
  config/api.yml
  spec/requests/host_initiators_spec.rb
Labels: enhancement

#996 [IVANCHUK] Fix storing ae_attributes as uri_attributes for create/edit in CustomButtons
  app/controllers/api/custom_buttons_controller.rb
  spec/requests/custom_buttons_spec.rb
Labels: bug

#1005 [config/api.yml] Fix for new miq_event identifiers
  config/api.yml
Labels: bug

#998 Add endpoint for time profiles.
  app/controllers/api/time_profiles_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/time_profiles_spec.rb
Labels: enhancement, kasparov/no

#1011 Convert `supports_#{op}?` to `supports?(op)`
  app/controllers/api/conversion_hosts_controller.rb
  app/controllers/api/host_aggregates_controller.rb
  app/controllers/api/mixins/service_templates.rb
  app/controllers/api/network_routers_controller.rb
  app/controllers/api/providers_controller.rb
  app/controllers/api/subcollections/security_groups.rb
  app/controllers/api/subcollections/snapshots.rb
Labels: refactoring

#1006 Added creation of new VolumeMapping
  app/controllers/api/volume_mappings_controller.rb
  config/api.yml
  spec/requests/volume_mappings_spec.rb
Labels: enhancement, providers/storage

#1012 Expose CloudSubnet create/edit form via OPTIONS
  app/controllers/api/cloud_subnets_controller.rb
  spec/requests/cloud_subnets_spec.rb
Labels: enhancement

#1010 Safe delete for cloud volume
  app/controllers/api/cloud_volumes_controller.rb
  config/api.yml
  spec/requests/cloud_volumes_spec.rb
Labels: enhancement, providers/storage

#999 Add endpoint for IsoImage.
  app/controllers/api/iso_images_controller.rb
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/iso_images_spec.rb
Labels: enhancement, kasparov/no

#1015 Renamed feature to match changes in MiqProductFeatures
  config/api.yml
Labels: enhancement

#993 Add simulate action for policy simulation.
  app/controllers/api/mixins/policy_simulation.rb
  app/controllers/api/vms_controller.rb
  config/api.yml
  spec/requests/vms_spec.rb
  spec/support/shared_examples/simulate_policy_action.rb
Labels: enhancement, kasparov/no
