Repository ManageIQ/manageiq-api, pull requests merged in 2021-04, with the labels that each got.

#1024 Replace the retire action with request_retire
  app/controllers/api/vms_controller.rb
  spec/requests/vms_spec.rb
Labels: bug

#1025 Add endpoint for cloud subnets
  app/controllers/api/cloud_subnets_controller.rb
  config/api.yml
  spec/requests/cloud_subnets_spec.rb
Labels: enhancement, kasparov/no, lasker/no

#1021 new POST API method allowing import of images from one provider into another
  app/controllers/api/cloud_templates_controller.rb
  config/api.yml
Labels: enhancement

#1026 Add api options for instance snapshot creation
  app/controllers/api/instances_controller.rb
Labels: enhancement, lasker/yes?

#1027 Fix User AR object dumped to logs
  app/controllers/api/providers_controller.rb
Labels: bug

#1029 Allow `id` as a method parameter name
  .rubocop_local.yml
Labels: developer

#1030 Remove Alberto from the CODEOWNERS to reduce his notifications
  .github/CODEOWNERS
Labels: developer

#1028 Add edit cloud volume function and route
  app/controllers/api/cloud_volumes_controller.rb
  config/api.yml
Labels: bug, lasker/yes?

#1031 Handle Unicode characters in httpd auth headers
  app/controllers/api/base_controller/authentication.rb
Labels: bug, lasker/yes?
