Repository ManageIQ/manageiq-api, pull requests merged in 2022-12, with the labels that each got.

#1189 Allow custom_actions option on physical infrastructure collections
  config/api.yml
Labels: enhancement, providers/physical

#1186 Remove IsoDatastore from API
  config/api.yml
  spec/requests/collections_spec.rb
  spec/requests/iso_datastores_spec.rb
Labels: enhancement, technical debt

#1190 Added endpoints for physical storage families, resources and services
  app/controllers/api/physical_storage_families_controller.rb
  app/controllers/api/storage_resources_controller.rb
  app/controllers/api/storage_services_controller.rb
  config/api.yml
  spec/requests/physical_storage_families_spec.rb
  spec/requests/storage_resources_spec.rb
  spec/requests/storage_services_spec.rb
Labels: enhancement
