Repository ManageIQ/manageiq-api, pull requests merged in 2022-06, with the labels that each got.

#1165 return task_id from widget refresh
  app/controllers/api/widgets_controller.rb
  spec/requests/widgets_spec.rb
Labels: bug, morphy/yes?, najdorf/yes?

#1164 Add cloud volume clone feature
  app/controllers/api/cloud_volumes_controller.rb
  config/api.yml
  spec/requests/cloud_volumes_spec.rb
Labels: enhancement

#1167 extract api_ems_resource from create_ems_resource
  app/controllers/api/base_controller/action.rb
Labels: refactoring

#1168 Handle params_for_create that take parameters
  app/controllers/api/base_controller/renderer.rb
Labels: bug

#1172 Add timeout-minutes to setup-ruby job
  .github/workflows/ci.yaml
Labels: developer
