Repository ManageIQ/manageiq-api, pull requests merged in 2022-01, with the labels that each got.

#1115 consolidate api.yml put/delete/patch with post
  app/controllers/api/base_controller/parser.rb
  config/api.yml
  spec/requests/custom_attributes_spec.rb
  spec/requests/notifications_spec.rb
  spec/requests/querying_spec.rb
  spec/requests/tenant_groups_spec.rb
  spec/support/api/helpers.rb
Labels: refactoring

#1108 Resource search klass
  app/controllers/api/authentications_controller.rb
  app/controllers/api/automation_requests_controller.rb
  app/controllers/api/base_controller.rb
  app/controllers/api/base_controller/renderer.rb
  app/controllers/api/cloud_subnets_controller.rb
  app/controllers/api/cloud_tenants_controller.rb
  app/controllers/api/cloud_volumes_controller.rb
  app/controllers/api/configuration_script_sources_controller.rb
  app/controllers/api/floating_ips_controller.rb
  app/controllers/api/groups_controller.rb
  app/controllers/api/host_aggregates_controller.rb
  app/controllers/api/hosts_controller.rb
  app/controllers/api/mixins/chargeback_assignment.rb
  app/controllers/api/mixins/service_templates.rb
  app/controllers/api/network_routers_controller.rb
  app/controllers/api/physical_storages_controller.rb
  app/controllers/api/policies_controller.rb
  app/controllers/api/providers_controller.rb
  app/controllers/api/provision_requests_controller.rb
  app/controllers/api/pxe_servers_controller.rb
  app/controllers/api/rates_controller.rb
  app/controllers/api/reports_controller.rb
  app/controllers/api/requests_controller.rb
  app/controllers/api/roles_controller.rb
  app/controllers/api/service_dialogs_controller.rb
  app/controllers/api/service_orders_controller.rb
  app/controllers/api/service_requests_controller.rb
  app/controllers/api/service_templates_controller.rb
  app/controllers/api/services_controller.rb
  app/controllers/api/subcollections/features.rb
Labels: technical debt

#1118 Fixed Templates and VM API
  app/controllers/api/mixins/genealogy.rb
  app/controllers/api/templates_controller.rb
  app/controllers/api/vms_controller.rb
  spec/requests/templates_spec.rb
Labels: bug
