Repository ManageIQ/manageiq-api, pull requests merged in 2022-05, with the labels that each got.

#1158 Cloud database OPTIONS spec test
  app/controllers/api/cloud_databases_controller.rb
  spec/requests/cloud_databases_spec.rb
Labels: enhancement, providers/cloud

#1159 condense api_actions to api_resource for vms
  app/controllers/api/vms_controller.rb
  spec/requests/vms_spec.rb
Labels: refactoring

#1161 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#1157 del host initiator
  app/controllers/api/host_initiators_controller.rb
  config/api.yml
Labels: enhancement, providers/physical, najdorf/yes?

#1162 Fix cloud_volume_snapshat_create_queue
  app/controllers/api/subcollections/cloud_volume_snapshots.rb
Labels: bug, wip, providers/cloud

#1146 Custom button set reorder API
  app/controllers/api/custom_button_sets_controller.rb
  config/api.yml
  spec/requests/custom_button_sets_spec.rb
Labels: enhancement

#1120 Add VM set_description action
  app/controllers/api/vms_controller.rb
  config/api.yml
  spec/requests/vms_spec.rb
Labels: enhancement

#1125 add queue_name for ems_operations
  app/controllers/api/base_controller/action.rb
  app/controllers/api/services_controller.rb
Labels: bug, providers/provisioning, morphy/yes?, najdorf/yes?
