Repository ManageIQ/manageiq-api, pull requests merged in 2022-02, with the labels that each got.

#1126 Remove Hakiri
  README.md
Labels: cleanup, developer

#1116 consolidate api create
  app/controllers/api/auth_key_pairs_controller.rb
  app/controllers/api/base_controller/action.rb
  app/controllers/api/cloud_subnets_controller.rb
  app/controllers/api/cloud_tenants_controller.rb
  app/controllers/api/cloud_volumes_controller.rb
  app/controllers/api/configuration_script_sources_controller.rb
  app/controllers/api/floating_ips_controller.rb
  app/controllers/api/host_aggregates_controller.rb
  app/controllers/api/host_initiator_groups_controller.rb
  app/controllers/api/host_initiators_controller.rb
  app/controllers/api/network_routers_controller.rb
  app/controllers/api/physical_storages_controller.rb
  app/controllers/api/volume_mappings_controller.rb
  spec/requests/auth_key_pairs_spec.rb
  spec/requests/cloud_subnets_spec.rb
  spec/requests/configuration_script_sources_spec.rb
  spec/requests/floating_ips_spec.rb
  spec/requests/host_initiator_groups_spec.rb
  spec/requests/host_initiators_spec.rb
  spec/requests/network_routers_spec.rb
  spec/requests/physical_storages_spec.rb
  spec/requests/volume_mappings_spec.rb
  spec/requests/widgets_spec.rb
Labels: refactoring

#1127 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-api.gemspec
Labels: developer, test

#1130 Add Build History Graph to README.md
  README.md
Labels: developer, test

#1131 Fix cloud_volumes safe_delete spec with stub_supports
  spec/requests/cloud_volumes_spec.rb
Labels: bug, test, morphy/yes

#1135 Move supports to api_resource
  app/controllers/api/base_controller/action.rb
  app/controllers/api/cloud_volumes_controller.rb
  app/controllers/api/physical_storages_controller.rb
Labels: enhancement

#1139 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
