Repository ManageIQ/manageiq-api, pull requests merged in 2023-03, with the labels that each got.

#1201 Adrian/740029 add delete and update to host initiator groups
  app/controllers/api/host_initiator_groups_controller.rb
  config/api.yml
  spec/requests/host_initiator_groups_spec.rb
Labels: enhancement

#1211 Fix Provider#verify_credentials
  app/controllers/api/providers_controller.rb
  spec/requests/providers_spec.rb
Labels: bug, petrosian/yes?

#1202 Host verify_credentials
  app/controllers/api/hosts_controller.rb
  config/api.yml
  spec/requests/hosts_spec.rb
Labels: enhancement

#1210 use stub_settings_merge in specs
  spec/requests/authentication_spec.rb
  spec/requests/widgets_spec.rb
Labels: test

#1212 Fix specs requiring memcached
  spec/requests/authentication_spec.rb
  spec/requests/users_spec.rb
Labels: bug, test

#1213 Run core security tests against api
  .github/workflows/ci.yaml
  lib/tasks_private/spec.rake
Labels: enhancement, petrosian/yes?

#1215 change `StorageServicesController` base class to `BaseProviderController`
  app/controllers/api/storage_services_controller.rb
Labels: bug

#1217 Add test for authentications
  spec/requests/hosts_spec.rb
Labels: test

#1214 Add workflows/workflow_instances controllers
  app/controllers/api/workflow_instances_controller.rb
  app/controllers/api/workflows_controller.rb
  config/api.yml
  spec/requests/workflow_instances_spec.rb
  spec/requests/workflows_spec.rb
Labels: enhancement
