Repository ManageIQ/manageiq-api, pull requests merged in 2023-02, with the labels that each got.

#1197 Add request_id logging to track a single request
  app/controllers/api/base_controller/logger.rb
  spec/requests/logging_spec.rb
Labels: enhancement

#1200 Log the session id for a persisted session
  app/controllers/api/base_controller/logger.rb
Labels: enhancement

#1198 storage service endpoint
  app/controllers/api/storage_services_controller.rb
  config/api.yml
  spec/requests/storage_resources_spec.rb
  spec/requests/storage_services_spec.rb
Labels: enhancement, providers/storage

#1207 Fix issues after core changes for partial match passwords
  lib/api.rb
  lib/api/environment.rb
  spec/requests/regions_spec.rb
Labels: bug, petrosian/yes?

#1208 Fix cloud_volume clone supports spec
  spec/requests/cloud_volumes_spec.rb
Labels: bug, test

#1206 Remove oVirt probes from provider spec
  spec/requests/providers_spec.rb
Labels: test
