Repository ManageIQ/manageiq-api, pull requests merged in 2023-05, with the labels that each got.

#1222 remove unneeded responders
  app/controllers/api/base_controller.rb
Labels: technical debt, dependencies

#1226 drop Vmdb::GlobalMethod#column_type
  lib/api/filter.rb
  spec/lib/api/filter_spec.rb
  spec/requests/categories_spec.rb
  spec/requests/querying_spec.rb
Labels: technical debt

#1218 storage service edit mode: check which attached resources are compliant to selected capabilities
  app/controllers/api/storage_services_controller.rb
  config/api.yml
Labels: enhancement, providers/storage
