Repository ManageIQ/manageiq-api, pull requests merged in 2024-08, with the labels that each got.

#1264 Use ruby 3.1 for code coverage
  .github/workflows/ci.yaml
Labels: developer, test

#1265 Query metric rollups using start_date derived from the first rollup
  spec/requests/providers_spec.rb
Labels: bug/sporadic test failure, radjabov/yes

#1267 Fix CloudNetworks spec with empty including()
  spec/requests/cloud_networks_spec.rb
Labels: bug, test
