Repository ManageIQ/manageiq-api, pull requests merged in 2024-02, with the labels that each got.

#945 Automatically generate an OpenApi specification
  config/openapi.json
  lib/manageiq/api/open_api/generator.rb
  lib/tasks/manageiq/api_tasks.rake
Labels: enhancement

#1246 Drop include_concern
  app/controllers/api/base_controller.rb
Labels: technical debt, rails7

#1220 Use standard create/update/delete features for Authentications
  app/controllers/api/authentications_controller.rb
  app/controllers/api/subcollections/authentications.rb
  lib/services/api/authentication_service.rb
  spec/requests/authentications_spec.rb
  spec/requests/configuration_script_payloads_spec.rb
Labels: refactoring

#1247 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#1250 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
